### PR TITLE
Adds MYMETA

### PR DESCRIPTION
**Pull request by JJ**
Also had to bump up version number because it errored with Module::Build and comment-out build_depends which didn't work and I couldn't find which module was it included

### CODE REVIEW

**Comment by chorny** [comment]
MYMETA files are generated files that must not be in distribution. See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

**Comment by JJ** [comment]
You are right, these should be META and not MYMETA. I'm following instructions from here http://neilb.org/2017/05/16/missing-metadata-files.html, in fact, this distribution was assigned to me.

**Comment by JJ** [comment]
Now it has the correct file name. Thanks for the correction.

**Comment by JJ** [comment]
Can someone please take care of this? Or review/comment?

**Comment by JJ** [comment]
Thanks!

**Pull request merged**
